### ISSUE TITLE
WAT?

### ISSUE THREAD

**Issue by pfalcon** [eltanin-os/ecore#1]
How this cute project differs from a bunch of other "small and fast" OSish projects? The site linked, https://eltan.in.net/ , gives about zero info.

**Comment by eadwardus** [comment]
Hello there.
Will assume you are asking about the entire project instead of ecore specifically. This project already has a considerable amount of tools produced, all of those has a good care to follow the cited goals and have a good design, and if you are interested i can give a more detailed  description about a specific tool, but for the general view you can give a look at this post i've made about it:
https://eadwardus.site/?blog/2019-12-31

Also, please consider using IRC (#eltanin-os at freenode.net) or contacting my email (eadwardus AT disroot DOT org) for questions, and keeping the github issues only for issues.

**Comment by pfalcon** [comment]
Thanks for reply!

> Will assume you are asking about the entire project instead of ecore specifically.

Yup, it's a common problem with these multi-repo projects spread around entire organization - you never no where to post generic reports. I hope you appreciate the fact that I spent a homework of selecting the most "core" repo of the project ;-).

> This project already has a considerable amount of tools produced

But how it differs from gazillion (ok, a few) of other similar projects? Don't get me wrong - I have a warm fuzzy feeling for "minimalist" projects, actually I'm part of the scene. And given that our target audience is ~ zilch, it's always fun to spend a dozen minutes on a hunch, and even a quick chat, of what made another guy enter that slippery slope and compare his "PR" efforts with that of others. So, did you already crash on the "center of the resistance", that being https://suckless.org/ , and started a flame thread on their mailing list? (Flame, because you both do effectively the same, but they do it wrong, for no 2 minimalists will ever agree on a definition of minimalism ;-) ). If you did, congrats, the "birth of project" checklist is passed ;-).

> https://eadwardus.site/?blog/2019-12-31

Great, thanks! A curious reader would notice that the best description of the project sits not on the project site, but somewhere away, unlinked.

> and keeping the github issues only for issues.

Sure, feel free to close, thanks for the reply, and good luck!

**Comment by eadwardus** [comment]
> But how it differs from gazillion (ok, a few) of other similar projects?

I would say that the bigger difference is that the ways to achieve the claimed goals are quite different, for instance the entire code of the project is written in C without using the standard libc. So most of the differences are internal, the further you go from it, the closer you get to the similarities in projects of this nature (take for example FreeBSD and Linux running the same DE, for the final user, in a first view, both are the same thing)

> So, did you already crash on the "center of the resistance", that being https://suckless.org/ , and started a flame thread on their mailing list? (Flame, because you both do effectively the same, but they do it wrong, for no 2 minimalists will ever agree on a definition of minimalism ;-) )

I would say that suckless has a different goal, that is minimalism, which is not a goal of this project of mine. The primary goals are simplicity and reliability, which is the reason of writing an alternative libc and rewriting the tools with it. So the goal is to achieve a complete OS, with a lot of simple and stable small pieces.

> A curious reader would notice that the best description of the project sits not on the project site, but somewhere away, unlinked.

This problem is real, this entire project is in lack of a good documentation. A better presentation is already in my plans, which will happen after i am able to make things more friendly (easy installation and gui)
